name: Zuri Whiteboard Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [develop, main]
  pull_request:
    branches: [main, develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: yarn build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
        
        # This job is to cache the node modules in order to reduce the time it would take to run
      - name: Use cached node_modules
        uses: c-hive/gha-yarn-cache@v2
        with:
         directory: whiteboard-client

         #this job installs intalls yarn dependencies on the github runner
         #and also to build the static files that would be transferred to server later
      - name: install Dependencies
        run: |
          npm update           
          cd whiteboard-client
          npm update
          npm run build     

      - name: Git Pull on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ZURI_MAIN_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/zc_plugin_whiteboard/
            git clean -fd
            git stash
            git fetch --all
            git reset --hard origin/develop
            git pull origin develop            
            cd /var/www/zc_plugin_whiteboard/whiteboard-server/
            yarn install
            yarn run build
            cd /var/www/zc_plugin_whiteboard/spa-root/
            yarn install
            yarn run build
            pm2 reload whiteboard 2>/dev/null || pm2 start app.js --name "whiteboard"
